
export const categoriesOptions = {
  category1: [
    "badminton",
    "basketbal",
    "běh",
    "florbal",
    "fotbal",
    "házená",
    "nohejbal",
    "ping pong",
    "plavání",
    "tenis",
    "volejbal",
  ],
  category3: ["hřiště otevřené", "hřiště placené", "tělocvična"],
  category5: [
    "Bohunice",
    "Brno-sever",
    "Brno-střed",
    "Bystrc",
    "Horní Heršpice",
    "Jundrov",
    "Kohoutovice",
    "Komárov",
    "Komín",
    "Královo pole",
    "Líšeň",
    "Maloměřice a Obřany",
    "Nový Lískovec",
    "Starý Lískovec",
    "Tuřany",
    "Vinohrady",
    "Černovice",
    "Žabovřesky",
    "Židenice",
    "MU",
    "Mendelu",
    "UO",
    "VUT",
  ],
  surface: [
    "antuka",
    "asfalt",
    "gumový povrch",
    "mondo",
    "parkety",
    "písek",
    "tartan",
    "tráva",
    "umělá tráva",
    "umělá tráva 3. generace",
    "umělý povrch",
    "umělý povrch (epdm)",
    "umělý povrch (pur)",
    "umělý povrch bez písku",
    "umělý povrch s pískem",
    "umělý povrch z plastu (nisaplast)",
  ],
  groupedByCategory3: [
    {
      category3: "hřiště otevřené",
      category1: ["basketbal", "florbal", "fotbal", "nohejbal", "volejbal"],
      category5: [
        "Bohunice",
        "Brno-sever",
        "Brno-střed",
        "Bystrc",
        "Horní Heršpice",
        "Jundrov",
        "Kohoutovice",
        "Komárov",
        "Komín",
        "Líšeň",
        "Černovice",
        "Žabovřesky",
        "Židenice",
      ],
      surface: [
        "asfalt",
        "písek",
        "tartan",
        "umělý povrch bez písku",
        "umělý povrch s pískem",
        "umělý povrch z plastu (nisaplast)",
      ],
    },
    {
      category3: "hřiště placené",
      category1: [
        "basketbal",
        "běh",
        "florbal",
        "fotbal",
        "házená",
        "nohejbal",
        "tenis",
        "volejbal",
      ],
      category5: [
        "Bohunice",
        "Brno-střed",
        "Bystrc",
        "Jundrov",
        "Kohoutovice",
        "Komárov",
        "Komín",
        "Královo pole",
        "Líšeň",
        "Maloměřice a Obřany",
        "Nový Lískovec",
        "Starý Lískovec",
        "Tuřany",
        "Černovice",
        "Židenice",
        "MU",
        "VUT",
      ],
      surface: [
        "antuka",
        "mondo",
        "tartan",
        "tráva",
        "umělá tráva",
        "umělá tráva 3. generace",
        "umělý povrch s pískem",
      ],
    },
    {
      category3: "tělocvična",
      category1: [
        "badminton",
        "basketbal",
        "florbal",
        "fotbal",
        "házená",
        "ping pong",
        "plavání",
        "tenis",
        "volejbal",
      ],
      category5: [
        "Bohunice",
        "Brno-střed",
        "Bystrc",
        "Jundrov",
        "Kohoutovice",
        "Komín",
        "Královo pole",
        "Nový Lískovec",
        "Starý Lískovec",
        "Tuřany",
        "Vinohrady",
        "Černovice",
        "Žabovřesky",
        "Židenice",
        "MU",
        "Mendelu",
        "UO",
        "VUT",
      ],
      surface: [
        "gumový povrch",
        "parkety",
        "umělý povrch",
        "umělý povrch (epdm)",
        "umělý povrch (pur)",
        "umělý povrch s pískem",
      ],
    },
  ],
  timestamp: "2024-06-21T15:07:26.849Z",
};

